"""add password

Revision ID: 16f3d02784cb
Revises: d8db2ab803b0
Create Date: 2026-02-07 23:34:59.978620

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '16f3d02784cb'
down_revision = 'd8db2ab803b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password', sa.String(), nullable=True))
    op.alter_column('tasks', 'task_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('accounts', 'password')
    # ### end Alembic commands ###
