"""add account type

Revision ID: 690a7907bb74
Revises: 915a15d330c2
Create Date: 2026-01-29 22:30:04.180665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690a7907bb74'
down_revision = '915a15d330c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
