"""add phone number and phone verified

Revision ID: 7361997025dc
Revises: 16f3d02784cb
Create Date: 2026-02-24 21:47:55.023531

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7361997025dc'
down_revision = '16f3d02784cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('is_phone_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_phone_verified')
    op.drop_column('accounts', 'phone_number')
    # ### end Alembic commands ###
