"""update default created add

Revision ID: d8db2ab803b0
Revises: 720f97e43705
Create Date: 2026-02-04 22:11:19.284835

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd8db2ab803b0'
down_revision = '720f97e43705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
